#server:
#  port: 9090
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userM
    username: root
    password: 12345678n
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
